// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyRBe45Ul6SBKxMsq-c8kQ1t14N1Dzf3k',
    appId: '1:900736948108:web:caa9f4e8c91d1ee12b28a9',
    messagingSenderId: '900736948108',
    projectId: 'login-app-8f344',
    authDomain: 'login-app-8f344.firebaseapp.com',
    storageBucket: 'login-app-8f344.firebasestorage.app',
    measurementId: 'G-3JB924KTSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRKr2DQIkGOk0UItMFymuNQE-FSXEjxtk',
    appId: '1:900736948108:android:98d22476300e330a2b28a9',
    messagingSenderId: '900736948108',
    projectId: 'login-app-8f344',
    storageBucket: 'login-app-8f344.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD1RRGweI5UPO0BPz8Nl6Sh26SpzToctg',
    appId: '1:900736948108:ios:3344b902573ab8532b28a9',
    messagingSenderId: '900736948108',
    projectId: 'login-app-8f344',
    storageBucket: 'login-app-8f344.firebasestorage.app',
    iosBundleId: 'com.example.loginAppTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD1RRGweI5UPO0BPz8Nl6Sh26SpzToctg',
    appId: '1:900736948108:ios:3344b902573ab8532b28a9',
    messagingSenderId: '900736948108',
    projectId: 'login-app-8f344',
    storageBucket: 'login-app-8f344.firebasestorage.app',
    iosBundleId: 'com.example.loginAppTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyRBe45Ul6SBKxMsq-c8kQ1t14N1Dzf3k',
    appId: '1:900736948108:web:c85ee1b36d0d0dfd2b28a9',
    messagingSenderId: '900736948108',
    projectId: 'login-app-8f344',
    authDomain: 'login-app-8f344.firebaseapp.com',
    storageBucket: 'login-app-8f344.firebasestorage.app',
    measurementId: 'G-E5ZXQHH2M6',
  );

}